#pragma once
#define DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES
#include <doctest/doctest.h>

#define REQUIRE DOCTEST_REQUIRE
#define CHECK DOCTEST_CHECK
#define REQUIRE_FALSE DOCTEST_REQUIRE_FALSE
#define CHECK_FALSE DOCTEST_CHECK_FALSE
#define REQUIRE_THROWS DOCTEST_REQUIRE_THROWS
#define CHECK_THROWS DOCTEST_CHECK_THROWS
#define REQUIRE_THROWS_AS DOCTEST_REQUIRE_THROWS_AS
#define CHECK_THROWS_AS DOCTEST_CHECK_THROWS_AS
#define REQUIRE_NOTHROW DOCTEST_REQUIRE_NOTHROW
#define CHECK_NOTHROW DOCTEST_CHECK_NOTHROW
#define INFO DOCTEST_INFO
#define UNSCOPED_INFO DOCTEST_UNSCOPED_INFO
#define FAIL DOCTEST_FAIL
#define SUCCEED DOCTEST_SUCCEED

#define SECTION(name) DOCTEST_SUBCASE(name)

// Custom TEST_CASE that handles both 1 and 2 arguments (ignoring the second argument for doctest)
#define TEST_CASE_1(name) DOCTEST_TEST_CASE(name)
#define TEST_CASE_2(name, tags) DOCTEST_TEST_CASE(name)
#define GET_TEST_CASE_MACRO(_1, _2, NAME, ...) NAME
#define TEST_CASE(...) GET_TEST_CASE_MACRO(__VA_ARGS__, TEST_CASE_2, TEST_CASE_1)(__VA_ARGS__)
